apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: workadventure
  namespace: workadventure
spec:
  gateways:
    - istio-system/gateway
  hosts:
    - chat.workadventure.victor.internal
    - play.workadventure.victor.internal
    - icon.workadventure.victor.internal
    - map-storage.workadventure.victor.internal
    - ejabberd.workadventure.victor.internal
  http:
    - route:
        - destination:
            host: workadventure-chat
            port:
              number: 80
    - route:
        - destination:
            host: workadventure-play
            port:
              number: 3000
    - route:
        - destination:
            host: workadventure-icon
            port:
              number: 8080
    - route:
        - destination:
            host: workadventure-map-storage
            port:
              number: 3000
    - route:
        - destination:
            host: workadventure-ejabberd
            port:
              number: 5443
